name: Check Code

on: push

jobs:
  check:
    name: Check the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v4
        with:
          key: "${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}"
          path: |
            ~/.bun/install/cache
      - uses: oven-sh/setup-bun@v2
      - run: make check
