name: Publish hub to npm

on:
  push:
    tags:
        - hub-v*

jobs:
  delivery-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/hub
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - run: bun install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
