name: Release Packages

on:
  push:
    branches:
      - develop

jobs:
  check:
    uses: ./.github/workflows/check.yml

  release-please:
    runs-on: ubuntu-latest
    needs:
      - check
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      hub--release_created: ${{ steps.release-please.outputs['packages/hub--release_created'] }}
      hub--tag_name: ${{ steps.release-please.outputs['packages/hub--tag_name'] }}
      dashboard--release_created: ${{ steps.release-please.outputs['packages/dashboard--release_created'] }}
      dashboard--tag_name: ${{ steps.release-please.outputs['packages/dashboard--tag_name'] }}
    steps:
      - name: release
        id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  delivery-hub:
    name: Delivery Hub ${{ needs.release-please.outputs.hub--tag_name }}
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: needs.release-please.outputs.hub--release_created
    defaults:
      run:
        working-directory: packages/hub
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          key: "${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}"
          path: |
            ~/.bun/install/cache
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - run: bun install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  delivery-dashboard:
    name: Delivery Dashboard ${{ needs.release-please.outputs.dashboard--tag_name }}
    runs-on: ubuntu-latest
    needs:
      - release-please
    if: needs.release-please.outputs.dashboard--release_created
    defaults:
      run:
        working-directory: packages/dashboard
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - uses: actions/cache@v4
        with:
          key: "${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}"
          path: |
            ~/.bun/install/cache
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - run: bun install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
